---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
  namespace: default
data:
  .dockerconfigjson: >-
    ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMXpZVzFoYmpwTVVITm5hM0pPTkZSUWNuTjRVSGhLVlVwbVJnbz0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQo=
type: kubernetes.io/dockerconfigjson