---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
  namespace: default
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJzdGQtMDMwLTEzIiwicGFzc3dvcmQiOiJoWjgyZDdENSIsImF1dGgiOiJjM1JrTFRBek1DMHhNenBvV2pneVpEZEVOUT09fX19Cg==
type: kubernetes.io/dockerconfigjson