---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
    rule_files:
       - "/config/*"
    scrape_configs:
    - job_name: 'backend'
      static_configs:
        - targets: ['backend:8081']